"""Builds website/ from the last demo run."""

from __future__ import annotations

import pathlib

from . import sitekit as sk

ROOT = pathlib.Path(__file__).resolve().parent.parent

META = {
    "name": "ICU Early-Warning Models",
    "slug": "icu-early-warning",
    "repo": "2.0-Healthcare-Ai-Systems",
    "pillar": "Healthcare Safety",
    "tagline": "Hypoxemia and hypotension prediction with calibration, uncertainty, "
               "and a false-alert comparison made at matched sensitivity against the "
               "alarm a ward actually uses.",
    "tags": [("4-hour horizon", ""), ("patient-level split", ""),
             ("isotonic calibration", ""), ("ensemble uncertainty", ""),
             ("synthetic cohort", "demo")],
    "banner": "This run used a synthetic ICU cohort generated by src/cohort.py. It is "
              "not patient data and carries no clinical meaning. Events are driven by "
              "a latent process the model cannot fully observe, so achievable "
              "performance is bounded well below 1.0 by construction — a synthetic "
              "cohort a model scores 0.99 on would teach you nothing. MIMIC-IV and "
              "eICU are credentialed and are not bundled here.",
}


def _event_section(ev: str, d: dict) -> str:
    rows = d["models"]
    fr = d["false_alert_reduction"]

    tbl = sk.table(
        ["Model", "AUROC", "AUPRC", "Brier", "ECE", "False alerts /100 obs"],
        [[name, f"{m['auroc']:.3f}", f"{m['auprc']:.3f}", f"{m['brier']:.4f}",
          f"{m['ece']:.4f}",
          f"{m['alarm_at_target_sens']['false_alerts_per_100_obs']:.2f}"]
         for name, m in rows.items()],
        numeric_cols=(1, 2, 3, 4, 5))

    ece_chart = sk.bar_chart(
        [(n, m["ece"]) for n, m in rows.items()], fmt="{:.4f}")

    best = rows["gradient boosting + isotonic"]
    rel = best["reliability"]
    rel_chart = sk.line_chart(
        [("perfect", [(0.0, 0.0), (1.0, 1.0)]),
         ("observed", [(r["predicted"], r["observed"]) for r in rel])],
        xlabel="predicted probability", ylabel="observed frequency")

    sel = d["selective_prediction"]
    sel_chart = sk.line_chart(
        [("AUROC", [(s["keep_frac"], s["auroc"]) for s in sel if s["auroc"] == s["auroc"]])],
        xlabel="fraction of cases kept (rest deferred to a human)", ylabel="AUROC")

    fr_tbl = sk.table(
        ["", "Ward alarm", "Calibrated model", "Change"],
        [["Sensitivity (matched)", f"{fr['baseline_sensitivity']:.3f}",
          f"{fr['model_sensitivity']:.3f}", "matched by construction"],
         ["False alerts", f"{fr['baseline_false_alerts']:,}",
          f"{fr['model_false_alerts']:,}",
          f"{fr['false_alert_reduction_pct']:.1f}% fewer"],
         ["Per 100 observations", f"{fr['baseline_per_100_obs']:.2f}",
          f"{fr['model_per_100_obs']:.2f}", ""]],
        numeric_cols=(1, 2))

    return f"""
<section>
  <h2>{ev.capitalize()} — {d['horizon_h']:.0f}-hour horizon</h2>
  <div class="stack-lg">
    <p class="mono" style="color:var(--muted);font-size:12.5px">
      train {d['n_train_patients']} patients / {d['n_train_rows']:,} rows &middot;
      test {d['n_test_patients']} patients / {d['n_test_rows']:,} rows &middot;
      test event rate {d['test_event_rate']:.2%}
    </p>
    {tbl}

    <h3>Calibration is where the model wins</h3>
    {ece_chart}
    <p>Expected calibration error, lower is better. The ward alarm's score is not a
    probability at all &mdash; it is a normalised vital &mdash; so its ECE of
    {rows['single-threshold alarm']['ece']:.3f} is expected. The point is the gap: after
    isotonic calibration the model's stated risk is within
    {best['ece']:.3f} of the observed frequency, which is what makes a number like
    "18% risk in the next four hours" safe to put in front of a clinician.</p>
    {rel_chart}

    <h3>False alerts, compared honestly</h3>
    {fr_tbl}
    <div class="note">
      <h3>Why matched sensitivity</h3>
      <p>Both systems are set to the same {fr['matched_sensitivity']:.0%} sensitivity
      before their false alerts are counted. Comparing alarm burden at different
      sensitivities is the most common way to make an alerting result look better than
      it is: any system can cut false alerts by catching fewer events.</p>
      <p>The reduction here is <strong>{fr['false_alert_reduction_pct']:.1f}%</strong> on
      synthetic data. That is the honest analogue of a false-alarm-reduction claim, and
      it is a good deal smaller than the figures usually quoted for this kind of system.</p>
    </div>

    <h3>Does the uncertainty estimate earn its place?</h3>
    {sel_chart}
    <div class="note">
      <h3>A negative result</h3>
      <p>The chart shows AUROC when the model defers its least-certain cases to a human.
      A useful uncertainty estimate would make AUROC <em>rise</em> as uncertain cases are
      removed. It falls &mdash; from {sel[0]['auroc']:.3f} keeping everything to
      {sel[-1]['auroc']:.3f} keeping only the most confident half.</p>
      <p>The ensemble spread is not identifying cases the model gets wrong. It is
      identifying cases with low predicted probability, where members agree because
      the answer is easy and the event rate is low. Brier improves across the same
      sweep for exactly that reason, which is why Brier alone would have hidden this.</p>
      <p>So the uncertainty estimate is reported and is <strong>not</strong> recommended
      for triage in its current form. Conformal prediction, which gives coverage
      guarantees rather than a spread, is the obvious next thing to try.</p>
    </div>
  </div>
</section>
"""


def build_site(results: dict) -> pathlib.Path:
    c = results["cohort"]
    metrics = sk.metric_grid([
        ("Patients", f"{c['n_patients']:,}", f"{c['patient_hours']:,.0f} patient-hours"),
        ("Observations", f"{c['n_observations']:,}", "30-minute resolution"),
        ("Hypoxemia", f"{c['hypoxemia_events']:,}",
         f"{c['hypoxemia_rate']:.2%} of observations"),
        ("Hypotension", f"{c['hypotension_events']:,}",
         f"{c['hypotension_rate']:.2%} of observations"),
    ])

    body = f"""
<section>
  <h2>The question the label encodes</h2>
  <div class="stack">
    <p>Not "is this patient deteriorating now" &mdash; a monitor answers that and needs
    no model. The label here is <strong>will this patient deteriorate in the next four
    hours</strong>, and rows where the event has already started are dropped, because
    predicting an event in progress is not early warning.</p>
    <p>Splitting is by patient, never by observation. Two windows from one patient share
    a baseline and a latent trajectory, so a random row split leaks the patient across
    train and test and inflates every number on this page. That single choice moves
    results more than any model change here.</p>
  </div>
</section>

<section>
  <h2>Cohort</h2>
  <div class="stack-lg">
    {metrics}
    <p class="mono" style="color:var(--muted);font-size:12.5px">
      generated {sk.esc(results['generated_at'])} &middot;
      {results['n_features']} features &middot; mean age {c['mean_age']}
    </p>
  </div>
</section>
{_event_section('hypoxemia', results['events']['hypoxemia'])}
{_event_section('hypotension', results['events']['hypotension'])}
<section>
  <h2>Reproduce it</h2>
  <div class="stack">
    <pre>cd icu-early-warning
pip install -r requirements.txt
python -m pytest tests/ -q
python -m src.demo</pre>
    <p>To run it on MIMIC-IV or eICU, replace <code>src/cohort.py</code> with a loader
    returning the same <code>Patient</code> shape. Nothing else changes.</p>
  </div>
</section>

<section>
  <h2>What this does not establish</h2>
  <div class="stack">
    <ul class="tight">
      <li>The cohort is synthetic. Every number here describes a generator, not a
      hospital, and none of it transfers to MIMIC-IV or eICU without being re-run.</li>
      <li>AUROC near 0.70 is what this generator permits, because events are driven by
      a latent the features only partly observe. It is neither a good nor a bad
      clinical result &mdash; it is not a clinical result at all.</li>
      <li>No external validation, no prospective evaluation, no site transfer.</li>
      <li>Alert fatigue is modelled as a count of false alerts. Real alarm burden
      depends on timing, clustering and who is in the room.</li>
      <li>The uncertainty estimate does not support selective prediction here, as
      shown above. It should not be used for triage.</li>
    </ul>
  </div>
</section>
"""
    return sk.build(ROOT, META, body, results)
