"""Builds website/ from the last demo run."""

from __future__ import annotations

import pathlib

from . import sitekit as sk

ROOT = pathlib.Path(__file__).resolve().parent.parent

META = {
    "name": "Physiological Waveform Pipeline",
    "slug": "physiological-waveform-pipeline",
    "repo": "2.0-Healthcare-Ai-Systems",
    "pillar": "Healthcare Safety",
    "tagline": "Signal-quality assessment, artifact rejection and feature extraction "
               "for high-frequency arterial waveforms — scored against known "
               "artifact locations rather than assumed to work.",
    "tags": [("125 Hz ABP", ""), ("5 quality rules", ""),
             ("scored rejection", ""), ("synthetic cohort", "demo")],
    "banner": "This run used a synthetic arterial-pressure cohort generated by "
              "src/synth.py. It is not patient data. Its value is that every artifact "
              "is injected at a known location, which is the only way to measure "
              "whether artifact rejection works instead of asserting that it does. "
              "MIMIC-IV Waveform and VitalDB are credentialed and are not bundled.",
}


def build_site(results: dict) -> pathlib.Path:
    c, d, rj = results["cohort"], results["dataset"], results["rejection"]
    sweep = results["step_sweep"]

    metrics = sk.metric_grid([
        ("Waveform-hours", f"{d['waveform_hours']:.2f}", f"{c['n_segments']} segments"),
        ("Windows accepted", f"{d['acceptance_rate']:.1%}",
         f"{d['n_accepted']} of {d['n_windows']}"),
        ("Rejection F1", f"{rj['f1']:.3f}",
         f"P {rj['precision']:.2f} / R {rj['recall']:.2f}"),
        ("Specificity", f"{rj['specificity']:.3f}", "clean windows kept"),
    ])

    rules_tbl = sk.table(
        ["Rule", "Catches", "Fired"],
        [["low_pulsatility", "Power outside the 0.7–3.5 Hz cardiac band — drift below, "
          "noise above", results["reject_reasons"].get("low_pulsatility", 0)],
         ["flatline", "Disconnection or a closed stopcock: a perfectly constant trace "
          "that every amplitude check passes", results["reject_reasons"].get("flatline", 0)],
         ["out_of_range", "Samples outside 20–220 mmHg",
          results["reject_reasons"].get("out_of_range", 0)],
         ["spikes", "Narrow transients — a jump immediately reversed",
          results["reject_reasons"].get("spikes", 0)],
         ["step_change", "Implausible sample-to-sample jump",
          results["reject_reasons"].get("step_change", 0)]],
        numeric_cols=(2,))

    sweep_chart = sk.line_chart(
        [("precision", [(r["delta_max_mmhg"], r["precision"]) for r in sweep]),
         ("recall", [(r["delta_max_mmhg"], r["recall"]) for r in sweep]),
         ("F1", [(r["delta_max_mmhg"], r["f1"]) for r in sweep])],
        xlabel="step-change threshold (mmHg)", ylabel="score")

    conf_tbl = sk.table(
        ["", "Detector rejected", "Detector accepted"],
        [["Truly contaminated", rj["tp"], rj["fn"]],
         ["Truly clean", rj["fp"], rj["tn"]]],
        numeric_cols=(1, 2))

    src_tbl = sk.table(
        ["Source", "Rate", "Access", "Bundled here"],
        [[s["name"], f"{s['fs_hz']} Hz", s["access"],
          "yes" if s["bundled"] else "no"] for s in results["sources"]])

    feat_tbl = sk.table(
        ["Feature", "Why an early-warning model wants it"],
        [["map_mmhg / sbp_mmhg / dbp_mmhg", "Baseline haemodynamics"],
         ["pulse_pressure", "Narrows before the mean falls in hypovolaemia"],
         ["heart_rate_bpm", "From detected systolic peaks, not a monitor feed"],
         ["hr_variability_ms", "Falls with autonomic impairment, often early"],
         ["sbp_slope_mmhg_per_min", "Trend within the window, not just its level"],
         ["pulse_pressure_variation", "Classic fluid-responsiveness signal"],
         ["sqi", "Carried forward so downstream models can weight by quality"]])

    body = f"""
<section>
  <h2>What the pipeline decides</h2>
  <div class="stack">
    <p>Per ten-second window: is this waveform trustworthy enough to derive features
    from? Both errors are expensive. Admitting artifact produces confident garbage in
    whatever model consumes it; rejecting good signal throws away the data an
    early-warning model needs.</p>
    <p>Every rule is a named check with a stated threshold rather than a learned score.
    A clinician asking why a window was dropped deserves a better answer than that the
    model said so.</p>
  </div>
</section>

<section>
  <h2>This run</h2>
  <div class="stack-lg">
    {metrics}
    <p class="mono" style="color:var(--muted);font-size:12.5px">
      generated {sk.esc(results['generated_at'])} &middot;
      {c['injected_artifacts']} artifacts injected across {c['segments_with_artifacts']}
      of {c['n_segments']} segments ({c['artifact_prevalence']:.0%} prevalence)
    </p>
    {conf_tbl}
  </div>
</section>

<section>
  <h2>The five rules</h2>
  <div class="stack-lg">
    {rules_tbl}
    <div class="note">
      <h3>The spike rule took three attempts, and the failures are instructive</h3>
      <p>Scoring the first difference against its own median flags <em>every systolic
      upstroke</em>, because an arterial upstroke genuinely is the largest
      sample-to-sample change in a clean window. That version rejected 99% of good data.</p>
      <p>Subtracting a five-sample running median does not fix it: the median lags a
      fast upstroke, so each beat leaves ten samples of large residual and a clean
      ten-second window scores about two hundred "spikes".</p>
      <p>What separates the two is direction, not magnitude. A pressure upstroke is
      monotone — consecutive differences share a sign for the whole rise. A spike goes
      up and comes straight back down. Requiring a sign reversal <em>and</em> a
      magnitude above the window's robust scale isolates transients without touching
      the pulse, which is what moved rejection F1 from 0.045 to
      {rj['f1']:.3f}.</p>
    </div>
  </div>
</section>

<section>
  <h2>Threshold sensitivity</h2>
  <div class="stack-lg">
    {sweep_chart}
    <div class="note">
      <h3>Which rule is worth sweeping</h3>
      <p>This sweep moved twice while the pipeline was built. Sweeping the SQI threshold
      gave a flat line, because SQI fires on 16 of {d['n_windows']} windows here. So did
      sweeping the spike threshold, once the spike detector worked — a detector that
      separates the classes cleanly makes its own threshold stop mattering.</p>
      <p>Step-change is what binds on this cohort, so that is what is swept. Which rule
      binds is a property of the data, not a constant, and on real records it will move
      again. A sweep over an inactive rule looks like a sensitivity analysis and tells
      you nothing.</p>
    </div>
  </div>
</section>

<section>
  <h2>Derived dataset</h2>
  <div class="stack-lg">
    <p>{d['n_feature_rows']:,} rows &times; {len(d['features'])} features, written to
    <code>data/derived_features.csv</code>. Only accepted windows reach this stage.</p>
    {feat_tbl}
  </div>
</section>

<section>
  <h2>Getting real data in</h2>
  <div class="stack-lg">
    {src_tbl}
    <p>The loaders in <code>src/loaders.py</code> return the same segment shape the rest
    of the pipeline consumes, so switching from synthetic to real records changes that
    one module and nothing else. MIMIC-IV Waveform needs a credentialed PhysioNet
    account and CITI human-subjects training — a real gate, and no result from this
    project can claim MIMIC scale until it has been passed.</p>
  </div>
</section>

<section>
  <h2>Reproduce it</h2>
  <div class="stack">
    <pre>cd physiological-waveform-pipeline
pip install -r requirements.txt
python -m pytest tests/ -q      # 17 tests
python -m src.demo</pre>
  </div>
</section>

<section>
  <h2>What this does not establish</h2>
  <div class="stack">
    <ul class="tight">
      <li>{d['waveform_hours']:.1f} synthetic waveform-hours. Real ICU records contain
      failure modes this generator does not model, and the rejection scores above
      will not survive contact with them unchanged.</li>
      <li>The generator and the detector were written by the same person. Scoring a
      detector on artifacts you chose to inject is a necessary first step and not an
      external validation.</li>
      <li>ABP only. No ECG, PPG, respiratory or capnography channels.</li>
      <li>No clinical outcome is attached to any window here, so nothing in this
      project speaks to patient benefit.</li>
    </ul>
  </div>
</section>
"""
    return sk.build(ROOT, META, body, results)
