"""Run the pipeline over a synthetic cohort and score artifact rejection."""

from __future__ import annotations

import json
import pathlib
import sys
from datetime import datetime, timezone

import numpy as np

from .synth import make_cohort, FS_DEFAULT
from .pipeline import (build_dataset, process_segment, reject_reason_histogram,
                       score_rejection)
from .loaders import describe_sources

ROOT = pathlib.Path(__file__).resolve().parent.parent


def step_sweep(segments, fs) -> list:
    """Sweep the rule that is actually binding on this cohort.

    Worth stating because it changed twice while this was built. Sweeping the
    SQI threshold gave a flat line (SQI fires on 16 of 1440 windows), and so did
    sweeping the spike threshold once the spike detector was fixed -- a working
    detector separates the classes so cleanly that its threshold stops
    mattering. A sweep over an inactive rule looks like a sensitivity analysis
    and tells you nothing.

    The step-change rule is what fires now, so that is what is swept. Which rule
    binds is a property of the cohort, not a constant, and on real data it will
    move again.
    """
    out = []
    for thr in (15.0, 25.0, 35.0, 45.0, 60.0, 80.0, 120.0):
        s = score_rejection(segments, fs, delta_max_mmhg=thr)
        out.append({"delta_max_mmhg": thr, "precision": s["precision"],
                    "recall": s["recall"], "f1": s["f1"],
                    "specificity": s["specificity"]})
    return out


def run() -> dict:
    fs = FS_DEFAULT
    cohort = make_cohort(n_segments=120, duration_s=120.0, fs=fs,
                         artifact_rate=0.45, seed=7)
    ds = build_dataset(cohort, fs, window_s=10.0,
                       out_path=ROOT / "data" / "derived_features.csv")
    rej = score_rejection(cohort, fs)
    hist = reject_reason_histogram(cohort, fs)
    sweep = step_sweep(cohort, fs)

    n_with_art = sum(1 for s in cohort if s.artifacts)
    results = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "is_synthetic": True,
        "data_source": "synthetic ABP cohort generated by src/synth.py",
        "cohort": {
            "n_segments": len(cohort),
            "segments_with_artifacts": n_with_art,
            "artifact_prevalence": round(n_with_art / len(cohort), 4),
            "fs_hz": fs,
            "injected_artifacts": sum(len(s.artifacts) for s in cohort),
        },
        "dataset": ds,
        "rejection": rej,
        "reject_reasons": hist,
        "step_sweep": sweep,
        "sources": describe_sources(),
    }
    (ROOT / "results").mkdir(exist_ok=True)
    (ROOT / "results" / "latest.json").write_text(
        json.dumps(results, indent=2) + "\n", encoding="utf8")
    return results


def run_real() -> dict:
    """Process real BIDMC recordings and check beat detection against the monitor.

    This is the first result in the project that an outside device can
    contradict. The bedside monitor computed a pulse rate from the same
    plethysmogram, once per second, using its own algorithm. If the pipeline's
    derived rate disagrees with it, the pipeline is wrong -- there is no
    generator to blame.
    """
    import sys as _sys
    _sys.path.insert(0, str(ROOT))
    import numpy as _np
    from data.load import load_records, to_segments

    from .quality import PPG_LIMITS

    records, prov = load_records(root=ROOT / "data")
    segments = to_segments(records)
    # BIDMC's PLETH channel is a plethysmogram in arbitrary units, so the
    # arterial-pressure plausibility band does not apply to it. Passing the
    # ABP limits here rejected every window of every recording.
    limits = PPG_LIMITS

    per_record, errors = [], []
    for rec, seg in zip(records, segments):
        rows, quals = process_segment(seg.signal, seg.fs, limits=limits)
        accepted = [q for q in quals if q.accepted]
        hrs = [r["heart_rate_bpm"] for r in rows
               if r.get("heart_rate_bpm") == r.get("heart_rate_bpm")]
        derived = float(_np.median(hrs)) if hrs else float("nan")

        ref_med, delta = None, None
        if rec["reference_rate"] is not None:
            finite = rec["reference_rate"][_np.isfinite(rec["reference_rate"])]
            if len(finite):
                ref_med = float(_np.median(finite))
                if derived == derived:
                    delta = derived - ref_med
                    errors.append(delta)

        per_record.append({
            "record": rec["record"],
            "duration_s": round(len(seg.signal) / seg.fs, 1),
            "windows": len(quals),
            "accepted": len(accepted),
            "accept_rate": round(len(accepted) / len(quals), 4) if quals else 0.0,
            "derived_hr_bpm": round(derived, 2) if derived == derived else None,
            "monitor_hr_bpm": round(ref_med, 2) if ref_med is not None else None,
            "reference_channel": rec["reference_channel"],
            "difference_bpm": round(delta, 2) if delta is not None else None,
        })

    agreement = None
    if errors:
        arr = _np.asarray(errors)
        agreement = {
            "n_records_compared": int(len(arr)),
            "median_difference_bpm": round(float(_np.median(arr)), 3),
            "mean_absolute_difference_bpm": round(float(_np.mean(_np.abs(arr))), 3),
            "max_absolute_difference_bpm": round(float(_np.max(_np.abs(arr))), 3),
            "within_5_bpm": int((_np.abs(arr) <= 5).sum()),
        }

    results = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "is_synthetic": False,
        "data_source": "PhysioNet BIDMC PPG and Respiration Dataset (open access); "
                       "see data/MANIFEST.json for file hashes and retrieval times",
        "provenance": prov,
        "channel_limits": {"units": limits.units, "lo": limits.lo,
                           "hi": limits.hi,
                           "step_limit": "60% of the window's own peak-to-peak"
                                         if limits.delta_max is None
                                         else limits.delta_max},
        "artifact_scoring_reported": False,
        "artifact_scoring_withheld_because": prov["artifact_scoring_withheld_because"],
        "pressure_values_suppressed_because":
            "PLETH is a photoplethysmogram, not an arterial line; a systolic "
            "pressure in mmHg is not something this signal measures",
        "per_record": per_record,
        "beat_detection_vs_monitor": agreement,
    }
    (ROOT / "results").mkdir(exist_ok=True)
    (ROOT / "results" / "latest-real.json").write_text(
        json.dumps(results, indent=2) + "\n", encoding="utf8")
    return results


def main_real() -> int:
    from data.datakit import FetchError
    try:
        r = run_real()
    except FetchError as exc:
        print(f"cannot run on real data: {exc}", file=sys.stderr)
        return 2
    pv = r["provenance"]
    print(f"source: {r['data_source']}")
    print(f"{pv['n_records']} recordings, channel {pv['channel']} at {pv['fs_hz']} Hz")
    print(f"\n{'record':<9}{'dur s':>8}{'windows':>9}{'accepted':>10}"
          f"{'derived':>9}{'monitor':>9}{'diff':>8}")
    for x in r["per_record"]:
        d = f"{x['derived_hr_bpm']:.1f}" if x["derived_hr_bpm"] else "-"
        m = f"{x['monitor_hr_bpm']:.1f}" if x["monitor_hr_bpm"] else "-"
        df = f"{x['difference_bpm']:+.1f}" if x["difference_bpm"] is not None else "-"
        print(f"{x['record']:<9}{x['duration_s']:>8.0f}{x['windows']:>9}"
              f"{x['accepted']:>10}{d:>9}{m:>9}{df:>8}")
    ag = r["beat_detection_vs_monitor"]
    if ag:
        print(f"\nbeat detection vs the bedside monitor, {ag['n_records_compared']} "
              f"recordings:")
        print(f"  median difference        {ag['median_difference_bpm']:+.2f} bpm")
        print(f"  mean absolute difference {ag['mean_absolute_difference_bpm']:.2f} bpm")
        print(f"  worst record             {ag['max_absolute_difference_bpm']:.2f} bpm")
        print(f"  within 5 bpm             {ag['within_5_bpm']}/"
              f"{ag['n_records_compared']}")
    else:
        print("\nno monitor reference available in the cached recordings")
    print("\nartifact scoring is NOT reported: " +
          r["artifact_scoring_withheld_because"])
    print(r["pressure_values_suppressed_because"])
    print("wrote results/latest-real.json")
    return 0


def main() -> int:
    if "--real" in sys.argv[1:]:
        return main_real()
    r = run()
    c, d, rj = r["cohort"], r["dataset"], r["rejection"]
    print(f"cohort: {c['n_segments']} segments @ {c['fs_hz']} Hz, "
          f"{d['waveform_hours']:.2f} waveform-hours")
    print(f"  artifacts injected: {c['injected_artifacts']} across "
          f"{c['segments_with_artifacts']} segments "
          f"({c['artifact_prevalence']:.0%} prevalence)")
    print(f"\nwindows: {d['n_windows']}, accepted {d['n_accepted']} "
          f"({d['acceptance_rate']:.1%})")
    print(f"derived rows: {d['n_feature_rows']} x {len(d['features'])} features")
    print(f"\nartifact rejection vs ground truth:")
    print(f"  precision {rj['precision']:.3f}  recall {rj['recall']:.3f}  "
          f"F1 {rj['f1']:.3f}  specificity {rj['specificity']:.3f}")
    print("\nwhich rule fired:")
    for k, v in list(r["reject_reasons"].items())[:6]:
        print(f"  {k:<28}{v:>6}")
    print("\nstep-change sweep (the binding rule on this cohort):")
    for s in r["step_sweep"]:
        print(f"  {s['delta_max_mmhg']:>5.0f} mmHg  P={s['precision']:.3f} "
              f"R={s['recall']:.3f} F1={s['f1']:.3f} spec={s['specificity']:.3f}")
    try:
        from .site import build_site
        build_site(r)
        print("\nwebsite/ rebuilt from this run")
    except Exception as exc:  # pragma: no cover
        print(f"\n(site not rebuilt: {exc})", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
