"""Run the pipeline over a synthetic cohort and score artifact rejection."""

from __future__ import annotations

import json
import pathlib
import sys
from datetime import datetime, timezone

import numpy as np

from .synth import make_cohort, FS_DEFAULT
from .pipeline import build_dataset, score_rejection, reject_reason_histogram
from .loaders import describe_sources

ROOT = pathlib.Path(__file__).resolve().parent.parent


def step_sweep(segments, fs) -> list:
    """Sweep the rule that is actually binding on this cohort.

    Worth stating because it changed twice while this was built. Sweeping the
    SQI threshold gave a flat line (SQI fires on 16 of 1440 windows), and so did
    sweeping the spike threshold once the spike detector was fixed -- a working
    detector separates the classes so cleanly that its threshold stops
    mattering. A sweep over an inactive rule looks like a sensitivity analysis
    and tells you nothing.

    The step-change rule is what fires now, so that is what is swept. Which rule
    binds is a property of the cohort, not a constant, and on real data it will
    move again.
    """
    out = []
    for thr in (15.0, 25.0, 35.0, 45.0, 60.0, 80.0, 120.0):
        s = score_rejection(segments, fs, delta_max_mmhg=thr)
        out.append({"delta_max_mmhg": thr, "precision": s["precision"],
                    "recall": s["recall"], "f1": s["f1"],
                    "specificity": s["specificity"]})
    return out


def run() -> dict:
    fs = FS_DEFAULT
    cohort = make_cohort(n_segments=120, duration_s=120.0, fs=fs,
                         artifact_rate=0.45, seed=7)
    ds = build_dataset(cohort, fs, window_s=10.0,
                       out_path=ROOT / "data" / "derived_features.csv")
    rej = score_rejection(cohort, fs)
    hist = reject_reason_histogram(cohort, fs)
    sweep = step_sweep(cohort, fs)

    n_with_art = sum(1 for s in cohort if s.artifacts)
    results = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "is_synthetic": True,
        "data_source": "synthetic ABP cohort generated by src/synth.py",
        "cohort": {
            "n_segments": len(cohort),
            "segments_with_artifacts": n_with_art,
            "artifact_prevalence": round(n_with_art / len(cohort), 4),
            "fs_hz": fs,
            "injected_artifacts": sum(len(s.artifacts) for s in cohort),
        },
        "dataset": ds,
        "rejection": rej,
        "reject_reasons": hist,
        "step_sweep": sweep,
        "sources": describe_sources(),
    }
    (ROOT / "results").mkdir(exist_ok=True)
    (ROOT / "results" / "latest.json").write_text(
        json.dumps(results, indent=2) + "\n", encoding="utf8")
    return results


def main() -> int:
    r = run()
    c, d, rj = r["cohort"], r["dataset"], r["rejection"]
    print(f"cohort: {c['n_segments']} segments @ {c['fs_hz']} Hz, "
          f"{d['waveform_hours']:.2f} waveform-hours")
    print(f"  artifacts injected: {c['injected_artifacts']} across "
          f"{c['segments_with_artifacts']} segments "
          f"({c['artifact_prevalence']:.0%} prevalence)")
    print(f"\nwindows: {d['n_windows']}, accepted {d['n_accepted']} "
          f"({d['acceptance_rate']:.1%})")
    print(f"derived rows: {d['n_feature_rows']} x {len(d['features'])} features")
    print(f"\nartifact rejection vs ground truth:")
    print(f"  precision {rj['precision']:.3f}  recall {rj['recall']:.3f}  "
          f"F1 {rj['f1']:.3f}  specificity {rj['specificity']:.3f}")
    print("\nwhich rule fired:")
    for k, v in list(r["reject_reasons"].items())[:6]:
        print(f"  {k:<28}{v:>6}")
    print("\nstep-change sweep (the binding rule on this cohort):")
    for s in r["step_sweep"]:
        print(f"  {s['delta_max_mmhg']:>5.0f} mmHg  P={s['precision']:.3f} "
              f"R={s['recall']:.3f} F1={s['f1']:.3f} spec={s['specificity']:.3f}")
    try:
        from .site import build_site
        build_site(r)
        print("\nwebsite/ rebuilt from this run")
    except Exception as exc:  # pragma: no cover
        print(f"\n(site not rebuilt: {exc})", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
