"""Loaders for real waveform sources.

Neither MIMIC-IV Waveform nor VitalDB is redistributable, and neither is
bundled here. These loaders are the seam: they return the same SynthSegment
shape the rest of the pipeline consumes, so switching from synthetic to real
data changes this module and nothing else.

MIMIC-IV Waveform requires a credentialed PhysioNet account and completion of
the CITI human-subjects training. That is a real gate, and no result from this
project can claim MIMIC scale until it has been passed.
"""

from __future__ import annotations

import pathlib

import numpy as np

from .synth import SynthSegment


def load_wfdb_record(path: str | pathlib.Path, channel: str = "ABP") -> SynthSegment:
    """Load one PhysioNet WFDB record.

    Requires the `wfdb` package, which is an optional dependency precisely
    because the data it reads is gated.
    """
    try:
        import wfdb  # type: ignore
    except ImportError as exc:  # pragma: no cover
        raise ImportError(
            "reading MIMIC-IV waveforms needs the `wfdb` package: pip install wfdb"
        ) from exc
    rec = wfdb.rdrecord(str(path))                      # pragma: no cover
    if channel not in rec.sig_name:                     # pragma: no cover
        raise KeyError(f"{channel} not in {rec.sig_name}")
    idx = rec.sig_name.index(channel)                   # pragma: no cover
    sig = np.asarray(rec.p_signal[:, idx], dtype=float)  # pragma: no cover
    sig = sig[~np.isnan(sig)]                           # pragma: no cover
    return SynthSegment(signal=sig, fs=float(rec.fs),   # pragma: no cover
                        label=str(path))


def load_csv(path: str | pathlib.Path, fs: float, column: int = 0) -> SynthSegment:
    """Load a plain CSV of samples. The lowest-friction real-data path."""
    arr = np.loadtxt(path, delimiter=",", ndmin=2)
    return SynthSegment(signal=arr[:, column].astype(float), fs=fs, label=str(path))


def describe_sources() -> list:
    return [
        {"name": "MIMIC-IV Waveform", "fs_hz": 125,
         "access": "credentialed PhysioNet account + CITI training",
         "loader": "load_wfdb_record", "bundled": False},
        {"name": "VitalDB", "fs_hz": 100,
         "access": "open registration, non-commercial licence",
         "loader": "load_csv (after export)", "bundled": False},
        {"name": "Synthetic cohort", "fs_hz": 125,
         "access": "generated by src/synth.py",
         "loader": "make_cohort", "bundled": True},
    ]
