"""Train, calibrate and evaluate the early-warning models."""

from __future__ import annotations

import json
import pathlib
import sys
from datetime import datetime, timezone

import numpy as np

from .cohort import make_cohort, cohort_stats, EVENTS
from .dataset import build, split_by_patient, FEATURE_NAMES
from .metrics import (alarm_stats, auprc, auroc, brier, ece, reliability,
                      threshold_at_sensitivity)
from .models import (EnsembleUncertainty, SingleThresholdAlarm, boosted,
                     calibrated, logistic, selective_prediction)

ROOT = pathlib.Path(__file__).resolve().parent.parent
TARGET_SENS = 0.80


def evaluate_event(patients, event: str, horizon_h: float = 4.0) -> dict:
    X, y, groups, _ = build(patients, event=event, horizon_h=horizon_h)
    tr, te = split_by_patient(groups, test_frac=0.3, seed=3)
    Xtr, ytr, Xte, yte = X[tr], y[tr], X[te], y[te]

    # Baseline: the single vital a ward alarm would watch for this event.
    key = "spo2_pct" if event == "hypoxemia" else "map_mmhg"
    base = SingleThresholdAlarm(FEATURE_NAMES.index(key), invert=True)
    base.fit(Xtr, ytr)

    models = {
        "single-threshold alarm": base,
        "logistic": logistic().fit(Xtr, ytr),
        "gradient boosting": boosted().fit(Xtr, ytr),
        "gradient boosting + isotonic": calibrated(boosted()).fit(Xtr, ytr),
    }

    ens = EnsembleUncertainty(boosted, n_members=8, seed=1).fit(Xtr, ytr)

    rows = {}
    for name, m in models.items():
        p = m.predict_proba(Xte)[:, 1]
        thr = threshold_at_sensitivity(yte, p, TARGET_SENS)
        rows[name] = {
            "auroc": round(auroc(yte, p), 4),
            "auprc": round(auprc(yte, p), 4),
            "brier": round(brier(yte, p), 5),
            "ece": round(ece(yte, p), 5),
            "alarm_at_target_sens": alarm_stats(yte, p, thr),
            "reliability": reliability(yte, p),
        }

    # The comparison the healthcare claim actually needs: at matched
    # sensitivity, how many fewer false alerts than the ward baseline?
    b = rows["single-threshold alarm"]["alarm_at_target_sens"]
    best_name = "gradient boosting + isotonic"
    g = rows[best_name]["alarm_at_target_sens"]
    reduction = {
        "compared": best_name,
        "matched_sensitivity": TARGET_SENS,
        "baseline_sensitivity": b["sensitivity"],
        "model_sensitivity": g["sensitivity"],
        "baseline_false_alerts": b["false_alerts"],
        "model_false_alerts": g["false_alerts"],
        "false_alert_reduction_pct": round(
            100.0 * (b["false_alerts"] - g["false_alerts"]) / b["false_alerts"], 2)
        if b["false_alerts"] else 0.0,
        "baseline_per_100_obs": b["false_alerts_per_100_obs"],
        "model_per_100_obs": g["false_alerts_per_100_obs"],
    }

    pe = ens.predict_proba(Xte)[:, 1]
    unc = ens.uncertainty(Xte)
    selective = [selective_prediction(yte, pe, unc, f)
                 for f in (1.0, 0.9, 0.8, 0.7, 0.6, 0.5)]

    return {
        "event": event,
        "horizon_h": horizon_h,
        "n_train_rows": int(tr.sum()), "n_test_rows": int(te.sum()),
        "n_train_patients": int(len(np.unique(groups[tr]))),
        "n_test_patients": int(len(np.unique(groups[te]))),
        "test_event_rate": round(float(yte.mean()), 5),
        "models": rows,
        "false_alert_reduction": reduction,
        "selective_prediction": selective,
        "ensemble_mean_uncertainty": round(float(unc.mean()), 5),
    }


def run() -> dict:
    patients = make_cohort(n_patients=400, hours=48.0, step_h=0.5, seed=11)
    stats = cohort_stats(patients)
    results = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "is_synthetic": True,
        "data_source": "synthetic ICU cohort generated by src/cohort.py",
        "cohort": stats,
        "n_features": len(FEATURE_NAMES),
        "target_sensitivity": TARGET_SENS,
        "events": {e: evaluate_event(patients, e) for e in EVENTS},
    }
    (ROOT / "results").mkdir(exist_ok=True)
    (ROOT / "results" / "latest.json").write_text(
        json.dumps(results, indent=2) + "\n", encoding="utf8")
    return results


def main() -> int:
    r = run()
    c = r["cohort"]
    print(f"cohort: {c['n_patients']} patients, {c['n_observations']:,} observations, "
          f"{c['patient_hours']:,.0f} patient-hours, {r['n_features']} features")
    for e in ("hypoxemia", "hypotension"):
        print(f"  {e}: {c[f'{e}_events']} events "
              f"({c[f'{e}_rate']:.2%} of observations, "
              f"{c[f'{e}_patients_affected']} patients)")

    for ev, d in r["events"].items():
        print(f"\n=== {ev} — {d['horizon_h']:.0f} h horizon ===")
        print(f"train {d['n_train_patients']} patients / {d['n_train_rows']:,} rows,  "
              f"test {d['n_test_patients']} / {d['n_test_rows']:,} rows, "
              f"event rate {d['test_event_rate']:.2%}")
        print(f"{'model':<32}{'AUROC':>8}{'AUPRC':>8}{'Brier':>9}{'ECE':>8}"
              f"{'FA/100':>9}")
        for name, m in d["models"].items():
            print(f"{name:<32}{m['auroc']:>8.3f}{m['auprc']:>8.3f}"
                  f"{m['brier']:>9.4f}{m['ece']:>8.4f}"
                  f"{m['alarm_at_target_sens']['false_alerts_per_100_obs']:>9.2f}")
        fr = d["false_alert_reduction"]
        print(f"at matched sensitivity {fr['matched_sensitivity']:.0%}: "
              f"false alerts {fr['baseline_false_alerts']} -> "
              f"{fr['model_false_alerts']} "
              f"({fr['false_alert_reduction_pct']:+.1f}%)")
        print("selective prediction (defer the least certain):")
        for s in d["selective_prediction"]:
            print(f"  keep {s['keep_frac']:.0%}  n={s['n']:<6} "
                  f"AUROC={s['auroc']}  Brier={s['brier']}")

    try:
        from .site import build_site
        build_site(r)
        print("\nwebsite/ rebuilt from this run")
    except Exception as exc:  # pragma: no cover
        print(f"\n(site not rebuilt: {exc})", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
